jpuri/react-draft-wysiwyg

js/src/components/RemoveControl/index.js
It does not affect because it's exported as default.
=> Wrong RemoveControl Component default class name

README.md
Some typo fix on README.md example
=> README.md update for import path

js/src/components/Editor/index.js
This PR provides the ability to add custom buttons to the toolbar
=> Ability to add custom buttons to the toolbar

docs/src/components/Docs/index.js, docs/static/main.css, js/src/components/Controls/Embedded/styles.css, js/src/components/Controls/Image/index.js, js/src/config/defaultToolbar.js
In response to https://github.com/jpuri/react-draft-wysiwyg/issues/220
=> Imge : Add default size override

.travis.yml, yarn.lock
fix: update yarn-lock
feat: add travis
=> feat: update yarn lock and add travis

js/src/components/Editor/index.js, js/src/i18n/zh.js
I add i18n locale file for Chinese locale with. 
Please take a review over it. 
Thank you for this library which is very handy and useful.
=> Add i18n for Chinese with locale:  zh.

js/src/components/Editor/index.js, js/src/i18n/zh.js
=> I18n chinese

js/src/components/Controls/Image/index.js
when upload image error, I must refresh browser now, so I fix this problem by reset image loading status
=> support upload image callback error handler

js/src/i18n/index.js, js/src/i18n/ru.js
I add i18n locale file for Russian locale with.
=> Add i18n for Russian with locale: ru

js/src/i18n/ru.js
I added russian translation for string *Open link in new window*. These changes were added in this (PR)[Open link in new window].
=> Added russian translation of 'Target blank'

js/src/renderer/Embedded/index.js
One file was missed in an earlier update. This change makes that final update.
=> Moving to newer style of importing PropTypes

js/src/components/Controls/BlockType/Component/index.js
The intention here is to fix this bug: https://github.com/jpuri/react-draft-wysiwyg/issues/294
=> I just set to use the blocks from the config file again

docs/src/components/Docs/index.js, js/src/i18n/index.js, js/src/i18n/ko.js
I think H1 is better than 제목1(which is Korean) for programmers,
but for general use, I translated those.
=> i18n for Korean(ko)

js/src/components/Controls/Embedded/Component/index.js
so it does not submit on click when it has a form parent
=> Add type=button to EmbeddedComponent

docs/static/main.css, src/controls/Inline/Component/styles.css
=> Add align items center style to inline option

src/i18n/zh.js
=> Update i18n for Chinese with locale: zh.

src/controls/Link/Component/index.js
Changes the use of span elements for labels to improve the accessibility
of the modal.
=> Uses HTML labels in Link modal

src/Editor/index.js
fixes #502 extract inline style when editorState or contentState is changed
=> extract inline style when editorState or contentState is changed

src/i18n/es.js, src/i18n/index.js
Added js to have the Spanish language.
=> Added Spanish translation

docs/src/components/Docs/Props/EditorStyleProp/index.js
Hi, I just wanted to help a bit here improving the docs.
Checked and there are not contribution guidelines so I hope will be enough with this desc.
Thanks for this module!
=> Minor fix on the docs

docs/src/components/Docs/Props/CustomizingToolbarProp/index.js
Fix incorrect prop in 'Customizing toolbar' example
toolbarOnFocus -> toolbarHidden
=> Small documentation fix

src/i18n/fr.js
fr.js translation correction for "components.controls.list.outdent"
=> fr.js translation correction

src/controls/Link/index.js
https://github.com/jpuri/react-draft-wysiwyg/issues/708
=> Fix: "Link" and "Unlink" actions are not working with right to left selection

.eslintrc, src/Editor/index.js, src/components/Dropdown/Dropdown/index.js, src/controls/BlockType/Component/index.js, src/controls/BlockType/index.js, src/controls/ColorPicker/Component/index.js, src/controls/ColorPicker/index.js, src/controls/Embedded/Component/index.js, src/controls/Embedded/index.js, src/controls/Emoji/index.js, src/controls/FontFamily/index.js, src/controls/FontSize/index.js, src/controls/History/index.js, src/controls/Image/Component/index.js, src/controls/Image/index.js, src/controls/Inline/index.js, src/controls/Link/Component/index.js, src/controls/Link/index.js, src/controls/List/index.js, src/controls/Remove/index.js, src/controls/TextAlign/index.js, src/decorators/Mention/Suggestion/index.js
Cleanup code to remove legacy react methods.
=> Code refactoring to get rid of legacy react lifecycle methods.

src/decorators/Link/__test__/linkDecoratorTest.js, src/decorators/Link/index.js, src/utils/url.js
=> Fix XSS in Link Target

README.md
Gen AI chatbot for React Draft Wysiwyg. Will help Developers understand this repository better. You can ask for code examples, installation guide, debugging help and much more.
=> Add React Draft Wysiwyg AI Bot in Readme
