jpuri/react-draft-wysiwyg

- js/src/components/Editor/index.js
- js/src/renderer/index.js
This PR allows the ability to render other entities than images or embeds.
We use it internally to render Tweets and Instagram Posts.
> Ability to specify custom block renderer

- js/src/components/Editor/index.js
Per issue #189 
We could pass through this specific prop if you're worried about ...props, but this seems like it could prevent future such PRs.
> allow passthrough of ...props to draft-js editor

- js/src/renderer/index.js
In a recent update the editor state is passed to the block renderer, however it is not passed to the user defined block renderer. This is solved by this PR.
This PR is based on master as develop didn't include the functionality.
> Passing editor state customBlockRenderer

- js/src/components/Editor/__test__/editorTest.js
- js/src/components/Editor/index.js
this is to add ```toolbarDisable``` for hiding the toolbar. Fixes https://github.com/jpuri/react-draft-wysiwyg/issues/232
> feat: adding toolbarDisable prop for hiding toolbar

- config/webpack.dev.config.js
I was not able to use `npm start` to run the playground editor while working on issue #241
This fixed the issue but the tests seemed to be broken from the ReactIntl addition, so I could not make sure they worked.
Tested on Linux 4.10.1-1-ARCH.
> Fixed web webpack.dev.config.js when using npm start

- .editorconfig
- .eslintrc
I add [.editorconfig](http://editorconfig.org/) for fix lint error in IDE. The rules:
```
end_of_line = crlf
indent_style = space
indent_size = 2
```
Also add [rule](http://eslint.org/docs/rules/linebreak-style) `linebreak-style` in `.eslintrc`:
```
"linebreak-style": [
"error",
"windows"
]
```
because all lines endings `\r\n`.
> Add .editorconfig for IDE and fix 'linebreak-style' rule for eslint

- js/src/i18n/en.js
- js/src/i18n/fr.js
I think it makes much more sense to translate "Target blank" with its actual meaning (as far as I understand), which is to open the link in a new window. So I translated "open link in a new window".
I would suggest to change "Target blank" with "Open link in a new window" in English too... I would happily add this to the PR if you agree.
In case I didn't understand what the "target blank" checkbox is for, please explain to me :)
Thanks a lot for this project, and thanks for all your hard work !
> added french translation of 'Target blank'

- js/src/components/Controls/Image/Component/index.js
It's very slow when open file dialog in chrome, usually takes 6-10s, change `accept="image/*"` to the specific image mime type will fix this.
> Fix bad performance when open file dialog in chrome

- js/src/components/Editor/styles.css
I notice the a width bug:
according to this post
https://stackoverflow.com/questions/17468733/difference-between-width-auto-and-width-100-percent
we should not set width: 100%, but width: auto instead.
> fix width bug

- js/src/components/Editor/styles.css
As all the width and height are set by content-box, if we introduce some style framework like bootstrap which reset box-sizing to border-box, the styles of this editor (especially the toolbar) will corrupt.
> set box-sizing style

- .travis.yml
- js/src/components/Editor/index.js
- Randomly generated `wrapperId` breaks server rendering
- Passing wrapper id to `onEditorStateChange` callback makes creating multiple editors easier. 
Consider the following:
```
class MyComponent extends React.Component {
constructor(props) {
super(props);
this.state = {};
this.editors = ['notes', 'content', 'foo', 'bar'];
this.editors.forEach((editorId) => {
this.state[`editor-${editorId}`] = '<p></p>';
});
this.onEditorChange.bind(this);
}
makeEditor(id = '', state) {
return (
<Editor
wrapperId={id}
onEditorStateChange={this.onEditorChange}
editorState={state}
/>
);
}
onEditorChange(editorState, id) {
this.setState({
[`editor-${id}`]: editorState
});
}
render() {
return (
this.editors
.map(editorId => this.makeEditor(editorId, this.state[`editor-${editorId}`]))
);
}
}
```
> Add wrapperId as prop

- src/controls/Image/Component/index.js
Prevent crash when drag and dropping image from another browser into the image uploader.
For #247
> Prevent crash when drag and dropping image from another browser.

- src/Editor/styles.css
Recent changes in commit c831168bae80d514daecd2536e65597fe6e2fd01 have polluted the styles for other `pre` and `blockquote` elements within our application. This pull request contains a change to limit the new styles to only be applied within the `rdw-editor-main` element.
This change assumes that the `pre` and `blockquote` would appear as descendants  of an element that uses the class name `rdw-editor-main`. I am not familiar enough with the project to know this is true with 100% confidence. But it seems correct.
> Limit pre and blockquote styles to only within the wysiwyg

- src/controls/Image/Component/index.js
When an image is added if you provide only numbers for height and width ( without units ) it won't work once you save the html and show it later.
Also a warning is shown in the console:
This fix handles that by automatically appending "px" to the number if no unit is specified.
> Append px to image size if units are not explicitly provided

- src/decorators/Mention/Suggestion/index.js
This is the proposed fix for #480.
Currently if a user presses 'Enter' when the mentions dropdown is showing, but has not selected an option, an error will be thrown. This first checks if there is a mention selected before it tries to add it.
> Check if the selected mention is valid

- src/i18n/en.js
A common English user would not recognize the terms "font family". Most English users refer simply to the "font".
> Change "Font Family" to "Font"

- src/i18n/en.js
The word "Highlight" is better suited to English users. 
"Background" is the term used in HTML; however, a common English user would think that the background color would change the background of the entire editor instead of the chosen text. The word "Highlight" more accurately describes the effect of changing the background behind a line of text.
> Change "Background" to "Highlight"

- src/decorators/Mention/Suggestion/index.js
Proposed fix for #86 
Currently a 
```
A component is `contentEditable` and contains `children` managed by React
```
warning comes up when you use mentions. Not a big deal, but very annoying when you have the console open. This PR suppresses those warnings.
> Fix content editable warning for mentions

- src/decorators/Mention/Suggestion/index.js
- src/decorators/Mention/addMention.js
Currently if you try to add a mention before a mention that you have already added previously, it does some weird things.
This PR just makes sure that you find the correct offset for the mention, no matter where you decide to put that mention.
First I write this:
`This is an @apple`
Then I decide to add another one:
`This is a @bana and an @apple`
Which brings up the mentions menu, I click on the BANANA option, and this happens:
`This is a @bana and an @banana and an @apple`
> Fixing adding mentions

- src/controls/Link/index.js
The correct key for a link `target`, such as `_blank` is `targetOption` instead of `target`
It looks like draft-js doesn't recognize the `target` key and ignores it when creating an `<a>` tag
> fix(Link): Update link creation

- src/controls/TextAlign/Component/index.js
As suggested in https://github.com/jpuri/react-draft-wysiwyg/issues/514
> Avoid error when an alignment is not defined. fixes #514

- docs/src/components/Demo/EditorConvertToHTML/index.js
There was an unused import in the first example at demo page. So I removed this one.
> Removed unused import

- src/controls/Image/Component/index.js
**What is the problem ?**
Some people might use cloudinary or other image upload services instead of imgur but their uploadCallback will fail on react-draft-wysiwyg because imageUpload assume the data reside at `data.link` instead of general `data.url`
**Comparison of popular image uploading api, assuming we use axios**
1. imgur (https://api.imgur.com/models/image)
uploaded image url is returned at `response.data.link`
2. cloudinary (https://cloudinary.com/documentation/upload_images#upload_response)
uploaded image url is returned at `response.data.secure_url` and `response.data.url`
**Proposed solution**
Fallback to `data.url` if `data.link` is not working. I think `url` is more general than `link` in API response
Cloudinary API for example, returns it in `data.url`
compared to Imgur API …
> Use data.url for imageUpload response handling instead of just data.link

- docs/src/components/Docs/Props/EditorRef/index.js
The [docs page](https://jpuri.github.io/react-draft-wysiwyg/#/docs) suggest `ref.focusEditor()` to focus - however the correct function name is `ref.focus()`
I've searched the docs and there is only this one reference to `focusEditor`.
> ref.focusEditor() --> ref.focus() - Changed example to reflect correct draft-js function name

- src/controls/BlockType/Component/styles.css
- src/controls/ColorPicker/Component/styles.css
- src/controls/Embedded/Component/styles.css
- src/controls/Emoji/Component/styles.css
- src/controls/FontFamily/Component/styles.css
- src/controls/FontSize/Component/styles.css
- src/controls/History/Component/styles.css
- src/controls/Image/Component/styles.css
- src/controls/Inline/Component/styles.css
- src/controls/Link/Component/styles.css
- src/controls/List/Component/styles.css
- src/controls/Remove/Component/styles.css
- src/controls/TextAlign/Component/styles.css
Resizing to mobile sometimes let the options overflow,
with flex-wrap: wrap on the wrappers, the options will take a spot in a new row when there is no sufficient space in the current row
without flex-wrap:
with flex-wrap on wrappers:
> Flex wrap options

- src/components/Dropdown/DropdownOption/index.js
- src/components/Option/index.js
Addresses #672 where dynamic classnames would evaluate an `undefined` prop. This adds a `defaultProps` to the components to ensure it will default to an empty string in the case that no class prop is passed.
> Add default props to prop classnames so they don't evaluate as undefined

- src/controls/BlockType/Component/index.js
This is to fix an issue when I was running mocha test for react-draft-wysiwyg. The idea is that the Array object in browsers always has includes() method. However if you run this in mocha or node, it will not be available. You have to enable the flag --harmony_array_includes. This can be done but the includes method can be replaced with indexOf() so that other developers do not have to google up for the issue.
https://github.com/nodejs/node/issues/5715
> changed includes to indexOf for Array object

- src/Editor/index.js
When the mention prop is used, while mounting the editor, the library breaks the app sends this message: "Cannot read property editorState of undefined", this is fixed by evaluating if `this.state` is defined first at `getEditorState` in `src/Editor/index.js`
Based in @git9am response in issue https://github.com/jpuri/react-draft-wysiwyg/issues/922#issuecomment-594379081
Fixes: https://github.com/jpuri/react-draft-wysiwyg/issues/922
Solves this error:
```
TypeError: Cannot read property 'editorState' of undefined
a.getEditorState
node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.js:7
```
> [FIX] Fixes editor error Cannot read property 'editorState' of undefined at initial loading, when mention prop is used
